### ISSUE TITLE
LinkSPI ASM Assembler Issues

### ISSUE THREAD

**Issue by GearsProgress** [rodri042/gba-link-connection#18]
Hello!

I'm currently using LinkSPI.hpp in one of my projects and it has been working really well! However, recently I have been getting some assembler errors:
```
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s: Assembler messages:
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3698: Error: MOV Rd, Rs with two low registers is not permitted on this architecture -- `mov R2,r7'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3701: Error: cannot honor width suffix -- `and R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3704: Error: cannot honor width suffix -- `orr R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3844: Error: MOV Rd, Rs with two low registers is not permitted on this architecture -- `mov R2,r7'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3847: Error: cannot honor width suffix -- `and R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3850: Error: cannot honor width suffix -- `orr R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3990: Error: MOV Rd, Rs with two low registers is not permitted on this architecture -- `mov R2,r6'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3993: Error: cannot honor width suffix -- `and R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:3996: Error: cannot honor width suffix -- `orr R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:4202: Error: cannot honor width suffix -- `and R0,R0,R1'
C:\Users\~1\AppData\Local\Temp\ccavpXSf.s:4205: Error: cannot honor width suffix -- `orr R0,R0,R1'
```

I'm having some issues figuring out exactly where the problem lies. If you have any tips on where I should look or any ideas what the problem may be, please let me know. Any assistance would be greatly appreciated!

Thank you!!

**Comment by afska** [comment]
Hey,

Hm... that was just an optimization I added in the last version. You can replace the asm code with `enableTransfer() ; startTransfer() ;`

Could you add details about your toolchain or what compiler are you using?

**Comment by afska** [comment]
I've removed the inline assembly. This was the result of a test where I was trying to determine why wireless multiboot wasn't working correctly and timing was critical. However, it turned out that the issue was actually a bug in the acknowledge procedure, so this change wasn't necessary.

Thanks for reporting this!
