### ISSUE TITLE
SDCard support?

### ISSUE THREAD

**Issue by ArcheyChen** [rodri042/gba-link-connection#19]
Hello, this is a nice project, I wonder if there is a plan to add SD card r/w support?

https://www.bilibili.com/video/BV1gH4y1m7ty/?vd_source=1af828ff5df4e67b0feb279fa0ee5cbf

I saw a video that using link cable to connect a sd card, it will be really useful for some hb to read external data.

**Comment by afska** [comment]
Hey! No plans for SD card via Link Port, sorry. But you may want to check out [gba-flashcartio](https://github.com/afska/gba-flashcartio), a library that allows reading the SD card in a flash cartridge (EverDrive GBA and EZ Flash Omega).

**Comment by ArcheyChen** [comment]
> Hey! No plans for SD card via Link Port, sorry. But you may want to check out [gba-flashcartio](https://github.com/afska/gba-flashcartio), a library that allows reading the SD card in a flash cartridge (EverDrive GBA and EZ Flash Omega).

I just want to write a lib for bootleg carts, they can be reflash now, but don't have external storage.
I'm not very good at embedding systems, but is the ` LinkSPI` in your project, theoretically, can direct connect to sd card, and I just need to write sd specific lib myself?

And is there any doc how to connect a SPI device via linkport?

**Comment by afska** [comment]
> I'm not very good at embedding systems, but is the  LinkSPI in your project, theoretically, can direct connect to sd card, and I just need to write sd specific lib myself?

Yes, `LinkSPI` can help you, but keep in mind that you might need to set some registers to use the SD card in SPI mode 3 (`CPOL=1, CPHA=1`) which is what GBA hardware uses.

> And is there any doc how to connect a SPI device via linkport?

This example illustrates how to connect a Link Cable to a Raspberry Pi's SPI pins:

https://github.com/afska/gba-remote-play?tab=readme-ov-file#normal-mode--spi

**Comment by afska** [comment]
I'm closing this issue as it doesn't involve coding on the gba-link-connection side, but feel free to continue commenting here if you have more questions and I'll try to answer them!
