### ISSUE TITLE
C Binding?

### ISSUE THREAD

**Issue by SquiddyGoat** [rodri042/gba-link-connection#21]
Are there any plans to create a sort of "C Binding" for this library, for use in plain C projects for the GBA?

**Comment by afska** [comment]
Hi! I'll try to look into this for the next release.

**Comment by SquiddyGoat** [comment]
Awesome! Thanks for the consideration 🙂

**Comment by afska** [comment]
hey @SquiddyGoat, you can now check out https://github.com/afska/gba-link-connection?tab=readme-ov-file#c-bindings

**Comment by SquiddyGoat** [comment]
> hey @SquiddyGoat, you can now check out https://github.com/afska/gba-link-connection?tab=readme-ov-file#c-bindings

Thank you! It was easy to set up, and it's working very well so far :)
