### ISSUE TITLE
Some clarifications on wireless adapter docs

### ISSUE THREAD

**Issue by corwinkuiper** [rodri042/gba-link-connection#9]
I'm just going through your improvements to the docs in detail in order to improve mine (yes, it has been a long while since you improved them!).

1. Regarding [IsConnectAttempt](https://github.com/rodri042/gba-link-connection/blob/master/docs/wireless_adapter.md#isconnectattempt---0x1a), it responds with a list of the connected adapters. My question is whether the 2 IDs fit in one value (due to IDs being 16 bits) or if each ID gets its own value.
2. Regarding [ReceiveData](https://github.com/rodri042/gba-link-connection/blob/master/docs/wireless_adapter.md#receivedata---0x26). So I don't think I had good evidence of the concatenation, I think I incorrectly extrapolated the limited data I had. I guess you confirmed this behaviour with more adapters than I have (I've got 2 adapters).
    - The header point seems strange to me. Given the format of the header is designed to make sure the headers from the clients don't overlap, my expectation would be for the headers to be ORed together.

If you have any logic captures from more than 2 adapters, I would love to see them.

**Comment by afska** [comment]
Hey Corwin,

1) Each ID gets its own value (if I recall correctly, the most significant byte is zero on each ID). I've used this behavior on the library [here](https://github.com/rodri042/gba-link-connection/blob/v5.0.2/lib/LinkWireless.h#L735) to calculate the player count based on the response size.
2) In all my tests the data was concatenated, and the first value in `ReceiveData`'s response was a different header (the one I described is the header that `SendData` expects). I didn't spend too much time analyzing the form of `ReceiveData`'s header. I imagine it's a bitfield indicating the packet size that was concatenated for each player.

I can make captures of a console connecting with other 3 LinkWireless_demo instances. Would that be helpful?
I don't have enough cartridges to perform the same test with commercial games.

**Comment by corwinkuiper** [comment]
1. Thanks for the clarification.
2. Ah, it's a different header.

If it's not too much trouble to get that capture it would be much appreciated. I think I'll buy some more wireless adapters anyway.

**Comment by afska** [comment]
[wireless-adapter-3player-traces.zip](https://github.com/rodri042/gba-link-connection/files/11473961/wireless-adapter-3player-traces.zip)

Here are captures of two different 3-player sessions. One was recorded as the host, the other one as a client.
